test_2: test_2.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o test_2 test_2.c -lcs50 -lm

clean:
	rm -f *.o a.out core test_2 log.txt

sigma: sigma.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o sigma sigma.c -lcs50 -lm

search: search.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o search search.c -lcs50 -lm

test_5: test_5.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o test_5 test_5.c -lcs50 -lm

	
strcmp: strcmp.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o strcmp strcmp.c -lcs50 -lm
	
compare: compare.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o compare compare.c -lcs50 -lm

students: students.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o students students.c -lcs50 -lm